#!/bin/bash
#PBS -l walltime=48:00:00
#PBS -l vmem=12gb
#PBS -l nodes=1:ppn=1
#PBS -N GRU_EWS_Unbal_vec_allages
#PBS -m bea
#PBS -o output_GRU_EWS_vec_allages.txt
#PBS -e error_GRU_EWS_vec_allages.txt


# conda activate spyder-env
source ~/anaconda3/bin/activate spyder-env
cd /home/d/dlr10/Documents/02_Statitics_modelling/4_Modelling_TS/06_GRU_EWS_vectorial/Unbalanced


python GRU_Unbalanced_EWS.py



