#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -l vmem=18gb
#PBS -l nodes=1:ppn=1
#PBS -N CURB_all
#PBS -m bea
#PBS -o output_CURB_all.txt
#PBS -e error_CURB_all.txt


# conda activate spyder-env
source ~/anaconda3/bin/activate spyder-env
cd /home/d/dlr10/Documents/02_Statitics_modelling/4_Modelling_TS/10_CURB_Modelling/All


python CURB_ts_GRU.py
python CURB_ts_LSTM.py
python CURB_sta_SVM.py
python CURB_sta_XGB.py




