#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l vmem=12gb
#PBS -l nodes=1:ppn=1
#PBS -N Interpolation_2019_2020
#PBS -m bea
#PBS -o output.txt
#PBS -e error.txt
#PBS -t 0-4

source ~/anaconda3/bin/activate spyder-env
cd /home/d/dlr10/Documents/01_Preprocessing/00_Data_2019_2020

# conda activate spyder-env

a=3000

# two parenthesis to make the maths work

echo python 02_01_Interpolation_eobs_2019_2020.py -p $((${PBS_ARRAYID}*$a)) $(((${PBS_ARRAYID}+1)*$a))
#python 02_01_Interpolation_eobs_2019_2020.py -p $((${PBS_ARRAYID}*$a)) $(((${PBS_ARRAYID}+1)*$a))
python 02_01_Interpolation_eobs_2019_2020.py -p $((${PBS_ARRAYID}))

python 02_02_consolidation_Interpolation_eobs_2019_2020.py


