#!/bin/bash
#PBS -l walltime=36:00:00
#PBS -l vmem=20gb
#PBS -l nodes=1:ppn=1
#PBS -N stats_2016_18
#PBS -m bea
#PBS -o stats_2016_18_output.txt
#PBS -e stats_2016_18_error.txt



# conda activate spyder-env
source ~/anaconda3/bin/activate spyder-env
cd /home/d/dlr10/Documents/02_Statitics_modelling/2_Statistics/TS_Statistical_analysis


# NOTE:two parenthesis to make the maths work



# Send the script

echo python TS_Statistics.py
python TS_Statistics.py



